How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain ?


Answer : - Lets us say that we have this matrix provided below
$$
\left(\begin{array}{cc} 
a & b\\
c & d
\end{array}\right)
\left(\begin{array}{cc} 
e & f\\ 
g & h
\end{array}\right)
$$

the answer of this would be

$$
\left(\begin{array}{cc} 
ae +bg & af + bh\\
ce + dg & cf + dh
\end{array}\right)
$$

So from this we can see that each element of this 2x2 matrix required 2 multiplication and 1 addtion therefore for the 4 element it would require 8 multiplication and 4 addtion in total

for the general $N\times K$ and $K\times M$ it would require $N \times K \times M$
 multiplication and $N \times K-1 \times M$
 additions

Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?

Answer:- 

In [33]:
import random
import numpy as np
import time
# Let us assume the values

n=200
k=300
m=400

#create function to create the ramdon matrix

def mat(n,k):
    return [[random.randint(1,100) for i in range(k)] for i in range(n)]

start_time = time.time()

nxk=mat(n,k)
kxm=mat(k,m)
result=mat(n,m)

for i in range(n):
        for j in range(m):
            for k in range(k):
                result[i][j] += nxk[i][k] * kxm[k][j]
time1=time.time()-start_time

# Now convert this into numpy array
start_time = time.time()
nxk=np.array(nxk)
kxm=np.array(kxm)
result=np.dot(nxk,kxm)

time2=time.time()-start_time

print('Time for the list of list method = ',time1)
print('Time for the numpy method = ',time2)


Time for the list of list method =  0.10509705543518066
Time for the numpy method =  0.03393077850341797


Finding the highest element in a list requires one pass of the array. Finding the second highest element requires 2 passes of the the array. Using this method, what is the time complexity of finding the median of the array? Can you suggest a better method? Can you implement both these methods in Python and compare against numpy.median routine in terms of time?

In [54]:
import random

def sort(array):
    x=int(len(array))
    array.sort(reverse=True)
    print('Largerst number = ', array[0])
    
    if x%2==0:
        print('median = ',x/2,x/2+1)
    else:
        print('median = ',(x+1/2))
    
    for i in range(1,x):
        if array[i]!=array[0]:
            return print("second largest = ", array[i])


import random

def find_median(arr):
    highest = float('-inf')
    second_highest = float('-inf')

    for num in arr:
        if num > highest:
            second_highest = highest
            highest = num
        elif num > second_highest:
            second_highest = num

    if len(arr) % 2 == 1:
        return highest
    else:
        return (highest + second_highest) / 2

start_time = time.time()

arr = [random.randint(1, 100) for _ in range(10)]


median = find_median(arr)

time1=time.time()-start_time

print(f"Array: {arr}")
print(f"Median: {median}")

start_time = time.time()

test_array = [random.randint(1,10000) for i in range(2000)]
sort(test_array)
time2=time.time()-start_time

start_time = time.time()

np.median(test_array)


time3=time.time()-start_time

print('Time for the for loop method method = ',time1)
print('Time for the sort method = ',time2)
print('Time for the numpy.meadian method = ',time3)


Array: [32, 50, 21, 31, 84, 68, 77, 12, 55, 22]
Median: 80.5
Largerst number =  9998
median =  1000.0 1001.0
second largest =  9995
Time for the for loop method method =  0.0
Time for the sort method =  0.008012771606445312
Time for the numpy.meadian method =  0.0


What is the gradient of the following function with respect to x and y?


Answer: We know that gradient of $x^{2} y +y^{3}sin(x)$
would be $\displaystyle \frac{\partial x^{2} y +y^{3}sin(x)}{\partial x} \hat{i}$ + $\displaystyle \frac{\partial x^{2} y +y^{3}sin(x)}{\partial y} \hat{j}$

this on solving would give $(2xy+y^{3}\cos(x))\hat{i}+(x^{2} y +3y^{2}sin(x))\hat{j}$

In [43]:
import jax
import jax.numpy as jnp

# Define a function to differentiate
def fun(x, y):
    return x**2 * y + y**3 * jnp.sin(x)

# Generate random numbers
x=np.random.uniform(1,100)
y=np.random.uniform(1,100)

x_cap = 2 * x * y + y**3 * np.cos(x)
y_cap = x**2 + 3 * y**2 * np.sin(x)
print("Grad of the given expression is =", x_cap, "i +", y_cap, "j")


# Use jax.grad with argnums
gradient = jax.grad(fun, argnums=(0, 1))(x,y)

# Print the result
print("Gradient of the given expression using JAX is:", gradient)

Grad of the given expression is = 396.0419174483615 i + 5886.664132175968 j
Gradient of the given expression using JAX is: (Array(396.0419, dtype=float32, weak_type=True), Array(5886.664, dtype=float32, weak_type=True))


Use sympy to confirm that you obtain the same gradient analytically.

In [17]:
from sympy import *
import random

x, y = symbols('x y')

init_printing(use_unicode=True)

exrp=x**2 * y + y**3 * sin(x)
i_cap=diff(exrp,x)
j_cap=diff(exrp,y)
print(i_cap,j_cap)
random.seed(43)

x_val=random.uniform(1,100)
y_val=random.uniform(1,100)
print(i_cap.subs({x:x_val,y:y_val}))
print(j_cap.subs({x:x_val,y:y_val}))


2*x*y + y**3*cos(x) x**2 + 3*y**2*sin(x)
36251.5307864555
-14566.1944709440


Create a Python nested dictionary to represent hierarchical information. We want to store record of students and their marks. Something like:

    2022
        Branch 1
            Roll Number: 1, Name: N, Marks:
                Maths: 100, English: 70 …
        Branch 2
    2023
        Branch 1
        Branch 2
    2024
        Branch 1
        Branch 2
    2025
        Branch 1
        Branch 2


In [38]:
diction={2022:
    {'Branch 1':{
        'Roll_Number': 1,' Name': 'Ameya','Marks':{'Maths': 100, 'English': 70}
      },
        'Branch 2':
            {'Roll_Number': 2,' Name': 'Bmeya','Marks':{'Maths': 100, 'English': 70}
             }
            },
    2023:
        {'Branch 1':{
        'Roll_Number': 3,' Name': 'Cmeya','Marks':{'Maths': 100, 'English': 70}
      },
        'Branch 2':
            {'Roll_Number': 4,' Name': 'Dmeya','Marks':{'Maths': 100, 'English': 70}
             }
            },
        2024:
             {'Branch 1':{
        'Roll_Number': 5,' Name': 'Emeya','Marks':{'Maths': 100, 'English': 70}
      },
        'Branch 2':
            {'Roll_Number': 6,' Name': 'Fmeya','Marks':{'Maths': 100, 'English': 70}
             }
            },
2025:
{'Branch 1':{
        'Roll_Number': 7,' Name': 'Gmeya','Marks':{'Maths': 100, 'English': 70}
      },
        'Branch 2':
            {'Roll_Number': 8,' Name': 'Hmeya','Marks':{'Maths': 100, 'English': 70}
             }
            }}

print(diction[2022])


#Using class
class StudentRecord:
    def __init__(self, year, branch, roll_number, name, marks):
        self.year = year
        self.branch = branch
        self.roll_number = roll_number
        self.name = name
        self.marks = marks

class StudentDatabase:
    def __init__(self):
        self.database = {}

    def add_student_record(self, student_record):
        if student_record.year not in self.database:
            self.database[student_record.year] = {}
        if student_record.branch not in self.database[student_record.year]:
            self.database[student_record.year][student_record.branch] = []
        self.database[student_record.year][student_record.branch].append({
            'Roll Number': student_record.roll_number,
            'Name': student_record.name,
            'Marks': student_record.marks
        })

    def display_database(self):
        for year, branches in self.database.items():
            print(f"{year}")
            for branch, students in branches.items():
                print(f"    {branch}")
                for student in students:
                    print(f"        Roll Number: {student['Roll Number']}, Name: {student['Name']}, Marks: {student['Marks']}")

# Example usage:
# Create instances of StudentRecord and add them to the database

student_db = StudentDatabase()

record1 = StudentRecord(2022, 'Branch 1', 1, 'N', {'Maths': 100, 'English': 70})
record2 = StudentRecord(2022, 'Branch 2', 2, 'M', {'Maths': 90, 'English': 80})
record3 = StudentRecord(2023, 'Branch 1', 3, 'P', {'Maths': 95, 'English': 75})

student_db.add_student_record(record1)
student_db.add_student_record(record2)
student_db.add_student_record(record3)

# Display the database
student_db.display_database()



{'Branch 1': {'Roll_Number': 1, ' Name': 'Ameya', 'Marks': {'Maths': 100, 'English': 70}}, 'Branch 2': {'Roll_Number': 2, ' Name': 'Bmeya', 'Marks': {'Maths': 100, 'English': 70}}}
2022
    Branch 1
        Roll Number: 1, Name: N, Marks: {'Maths': 100, 'English': 70}
    Branch 2
        Roll Number: 2, Name: M, Marks: {'Maths': 90, 'English': 80}
2023
    Branch 1
        Roll Number: 3, Name: P, Marks: {'Maths': 95, 'English': 75}


Using matplotlib plot the following functions on the domain: x = 0.5 to 100.0 in steps of 0.5.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0.5,100.5,0.5)
#x=y
y=x
plt.figure()
plt.plot(x,y,label="x=y")

y=x**2
plt.figure()
plt.plot(x,y,label="y=x^2")

y=np.sin(x)
plt.figure()
plt.plot(x,y,label="y=sin(x)")

y=np.sin(x)/x
plt.figure()
plt.plot(x,y,label="y=sin(x)/x")

y=np.log(x)
plt.figure()
plt.plot(x,y,label="y=log(x)")

y=np.exp(x)
plt.figure()
plt.plot(x,y,label="y=e^(x)")

Using numpy generate a matrix of size 20X5 containing random numbers drawn uniformly from the range of 1 to 2. Using Pandas create a dataframe out of this matrix. Name the columns of the dataframe as “a”, “b”, “c”, “d”, “e”. Find the column with the highest standard deviation. Find the row with the lowest mean.

In [ ]:
import pandas as pd
import numpy as np


matrix=np.random.uniform(1,2,size=(20,5))

print(matrix)

matrix=pd.DataFrame(matrix)

matrix.columns=['a','b','c','d','e']

print(matrix)

Std_Dev=matrix.std().sort_values(ascending=False)
print(matrix.std())

print("THe highest standard deviation is  ",Std_Dev[0])

matrix['Mean']=(matrix['a']+matrix['b']+matrix['c']+matrix['d']+matrix['e'])/5
print(matrix)

print('The minimum value of the mean is ',matrix['Mean'].min())

Add a new column to the dataframe called “f” which is the sum of the columns “a”, “b”, “c”, “d”, “e”. Create another column called “g”. The value in the column “g” should be “LT8” if the value in the column “f” is less than 8 and “GT8” otherwise. Find the number of rows in the dataframe where the value in the column “g” is “LT8”. Find the standard deviation of the column “f” for the rows where the value in the column “g” is “LT8” and “GT8” respectively.


In [27]:
import pandas as pd
import numpy as np


matrix=np.random.uniform(1,2,size=(20,5))

print(matrix)

matrix=pd.DataFrame(matrix)

matrix.columns=['a','b','c','d','e']



matrix['F']=(matrix['a']+matrix['b']+matrix['c']+matrix['d']+matrix['e'])

matrix['G']=np.where(matrix['F']<8,'LT8','GT8')
LT8=(matrix['G']=='LT8').sum()

std_LT8=matrix[matrix['G']=='LT8']["F"].std()

std_GT8=matrix[matrix['G']=='GT8']["F"].std()

print(matrix)
print("",LT8)
print(std_GT8)
print(std_LT8)

[[1.3971383  1.01615019 1.96120082 1.60403031 1.56491923]
 [1.97296106 1.45709537 1.33541861 1.52448978 1.08267202]
 [1.47320037 1.0008576  1.67578643 1.56019641 1.15750765]
 [1.33978256 1.54122685 1.46817215 1.17930139 1.22368399]
 [1.41571538 1.24886423 1.13187649 1.95829587 1.18939363]
 [1.27136861 1.32055588 1.58587499 1.4500214  1.59594165]
 [1.77231595 1.39009488 1.22630362 1.02024068 1.62525068]
 [1.37097218 1.76437639 1.28813715 1.35042714 1.41124004]
 [1.82699964 1.32068196 1.39162419 1.24612069 1.46882591]
 [1.73947683 1.31179594 1.65056358 1.35408274 1.04730884]
 [1.71013237 1.54003321 1.97701468 1.70805023 1.99002063]
 [1.73920783 1.36813106 1.12957686 1.17697718 1.56433971]
 [1.06950024 1.54441771 1.50199408 1.99176212 1.66498776]
 [1.00342055 1.37472267 1.04795381 1.39552228 1.86201094]
 [1.2547384  1.66919192 1.17336654 1.73450883 1.07604159]
 [1.42371446 1.28986621 1.36552003 1.92774232 1.86849808]
 [1.10403129 1.33101624 1.63441213 1.25222278 1.36396466]
 [1.86750716 1

In [31]:
class employee:
    def __init__(self,first,last,pay):
        self.first=first
        self.last=last
        self.pay=pay
        self.email= first+'.'+last+'@company.com'

emp_1=employee('Ameya',"Tajne",900948)

print(emp_1.pay)

900948


Write a small piece of code to explain broadcasting in numpy.

In [41]:
import numpy as np

#If we have two 1x4 matrix and perform this basic task 

A=np.array([1, 2, 3, 4])
B=np.array([2, 3, 5, 6])

print(A+B)

#There is no broadcasting error
#Now what if we add/substract 1x4 matrix with 1x3 matrix

A=np.array([1, 2, 3, 4])
B=np.array([2, 3, 5])

print(A+B)

#WE get this broadcasting error
#ValueError: operands could not be broadcast together with shapes (4,) (3,)

#But what would happen if we perform addtion on 1X3 and 3x1 matrix ?

A=np.array([1, 2, 3])
B=np.array([[2], [3], [5]])

print(A+B)

#We get the seemless addition

[ 3  5  8 10]
[[3 4 5]
 [4 5 6]
 [6 7 8]]


Write a function to compute the argmin of a numpy array. The function should take a numpy array as input and return the index of the minimum element. You can use the np.argmin function to verify your solution.

In [52]:
import numpy as np 
import random

def fun(x):
    n=int(len(x))
    min=x[0]
    for i in range (1,n):
        if x[i]<=min:
            min_ind=i
            min=x[i]
            
    return min_ind



        

x=[np.random.uniform(1,100) for i in range(10)]

print(x)
print("using the custom function the argmin = ",fun(x))

print("using the argmin the argmin is ",np.argmin(x))

[63.873200401113294, 13.159772980533324, 84.79570340892924, 24.507891425243344, 85.65497058173044, 83.74953898027863, 34.861301390775736, 41.52700660405151, 52.92748829817764, 22.848897745087257]
using the custom function the argmin =  1
using the argmin the argmin is  1
